version: '3.8'

services:
  web:
    build: ./webdev
    command: gunicorn rtdb.wsgi -b 0.0.0.0:8000
    volumes:
      - ./webdev/:/home/rtdb
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web